Add Contact form and Footer
waiyankyaw961999/Microverse-portofolio pull request #3
Opened 2023-05-02 07:13 UTC by waiyankyaw961999

### Add contact form and Footer
---

- [ ] Add a contact form section
- [ ] Add a footer section
- [ ] Add a style for contact form using grid 
- [ ] Add media query

2023-05-02 07:32 UTC, Umuhan commented on index.html
>                </button>
- [ ] Please use hover link in the button.

2023-05-02 07:33 UTC, kit0-0 commented on index.html
> +        <form action="#" class="flex flex-col">
kindly use an action to collect the data
`<form action="https://formspree.io/f/{form_id}" method="post">`

2023-05-02 07:34 UTC, Umuhan commented on index.html
> +          />
- [ ] Please indecate the the action here.

2023-05-02 07:47 UTC, malikhaiderkhan commented on index.html
> +        <form action="#" class="flex flex-col">
Please use the action attribute that where the data is going after submitting the form.
``` <form action="https://...." method="post/get">```

2023-05-02 07:48 UTC, malikhaiderkhan commented on styles/contact.css
Kindly use the button interactions as it is the requirement of the project.

2023-05-02 20:38 UTC, vickymarz requested changes
Hi @waiyankyaw961999, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- Form submitted successfully ✅ 
- The PR title and description are professional and descriptive ✅ 
- Good UI design ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 20:38 UTC, vickymarz commented on index.html
> +            maxlength="30"
- [ ] Kindly remove the max length validation that you added to your email input which is not a requirement for this project. 

Note: some users can have long emails 😄

2023-05-02 20:38 UTC, victorokoroji commented on index.html
> +          </button>
- [ ] Kindly implement your button interactions such as hover, active (when it's pressed), disabled, and enable (default state) styled as shown in the Figma template.

![image](https://user-images.githubusercontent.com/63473584/235780376-2905003e-a0fe-416a-b35a-e86a41df5327.png)

2023-05-04 04:51 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi team @waiyankyaw961999, @mohamedgamaleldin999999, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif)

## Highlights 🎉 
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Very nice design. 💯
✅ Incorporates feedback from previous code reviews.
✅ Pull request has a descriptive title and summary.

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-04 04:51 UTC, merged