Feature responsive design
waiyankyaw961999/Microverse-portofolio pull request #9
Opened 2023-05-04 11:03 UTC by waiyankyaw961999

## Add responsive design for all devices

1. Break points are 1090px , 768px, 430px
2. Add extra backgrounds in the behind the context for medium devices and large devices

2023-05-04 11:42 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @waiyankyaw961999 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️linters are passing
✔️correct use of github flow
✔️professional documentation
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 11:42 UTC, tugsem commented on styles/work-section.css
> +  }
- [ ] In the figma design, there are six work cards but you have seven. Kindly remove one and also, the horizontal gaps between them should be smaller than you used. I am attaching the images below:
yours: 
![image](https://user-images.githubusercontent.com/91486791/236191580-844690c8-1605-4b7c-b57c-65f95eaf4953.png)
figma: 
![image](https://user-images.githubusercontent.com/91486791/236191946-d8100763-1a7a-4f02-9654-a940e8cd90df.png)

2023-05-04 11:42 UTC, tugsem commented on styles/info.css
> +    row-gap: 32px;
- [ ] Please use the same proportioning for this section of cards. Each card should have the same layout for the title and should have more padding on the list underneath:
yours:
![image](https://user-images.githubusercontent.com/91486791/236192959-d98ff5f3-3691-411f-8309-816cb02ed969.png)
figma: 
![image](https://user-images.githubusercontent.com/91486791/236193040-7c2703d9-4570-4882-a8c8-7fdc70e80722.png)

2023-05-04 11:42 UTC, tugsem commented on styles/contact.css
> +    justify-items: center;
- [ ] Please use Flexbox to align items in this section. That would be more accurate. Also, please add the background image to match the figma design: 
yours: 
![image](https://user-images.githubusercontent.com/91486791/236193807-188cf901-24d4-4f81-9d0f-89dd865d9608.png)
figma: 
![image](https://user-images.githubusercontent.com/91486791/236193890-625cd6cb-6da8-46e0-a480-5e1a762e0346.png)

2023-05-05 19:01 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @waiyankyaw961999, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/5f6b955314ad7a8c010bb5de56877a2fa40a6d2bc5aeabd629e6a150f73afd97/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966" width="375px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] GitHub flow is used correctly :white_check_mark:  
- [x] Application is deployed using GitHub pages :white_check_mark: :clap: :clap:  
- [x] Pull request has a descriptive title and summary :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 13:22 UTC, merged